
- name: Création du Bastion
  azure.azcollection.azure_rm_bastionhost:
    resource_group: "{{ resource_group }}"
    name: "{{ bastion_name }}"
    ip_configurations:
      - name: testip
        subnet:
          id: "{{ subnetbast.state.id }}"
        public_ip_address:
          id: "{{ publicIPbast.publicipaddresses[0].id }}"
        private_ip_allocation_method: Dynamic
    sku:
      name: Standard
    enable_tunneling: True
    enable_shareable_link: False
    enable_ip_connect: False
    enable_file_copy: False
    scale_units: 6
    disable_copy_paste: False
- name: Création d'une ressource Azure PostgreSQL
  azure_rm_postgresqlserver:
    resource_group: "{{ resource_group }}"
    name: "{{ psql_server_name }}"
    sku:
      name: B_Gen5_1
      tier: Basic
    location: "{{ local }}"
    storage_mb: 5120
    enforce_ssl: False
    version: 11
    storage_autogrow: True
    admin_username: "{{ admin_name }}"
    admin_password: "{{ password }}"
- name: Création de la base de données
  azure_rm_postgresqldatabase:
    resource_group: "{{ resource_group }}"
    server_name: "{{ psql_server_name }}"
    name: "{{ database_name }}"
- name: Création règle firewall
  azure_rm_postgresqlfirewallrule:
    resource_group: "{{ resource_group }}"
    server_name: "{{ psql_server_name }}"
    name: authorizing_vmapp
    start_ip_address: "{{ ippub.state.ip_address }}"
    end_ip_address: "{{ ippub.state.ip_address }}"
- name: Création de la VM
  azure_rm_virtualmachine:
    resource_group: "{{ resource_group }}"
    name: "{{ vm_app_name }}"
    vm_size: "{{ vm_size }}"
    admin_username: "{{ admin_name }}"
    ssh_password_enabled: false
    ssh_public_keys:
      - path: "/home/{{ admin_name }}/.ssh/authorized_keys"
        key_data: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC6weIM5RegM8nd65pTC3LbEK30f4CnsaXiF/wfa6MZyUF+ueBSsECahrqjh6CyfahwiRZ0tAY9Bg4FX4C3yteps61AFJ4q11Gon3vZcNvOOqeQYEQHo+PtA47TNbUbVSAnuMiPyJY37JCDMtOI21URHTRzQp8jfVsJ6r6lKY/GNxH+3L9KEGKLUdVREcP9+6maFdCmGFDx+0zPrBWEPnDtb3OcJ8WSrpwK3Im6ty1JqEMlniHOxLEmnDNSfrrBFsLVjNKtPwjZA3H/3OypgPa/8jGTUXOmeQNI3uDCOVy8BchfK2+GlpzE6eutb2o7ldGF45+ErWcnTQIHsMTNM0RIDe9bSw0jEt8bqajxNXsLbZbbssp0sakdtogWn8WPHDBnedVRNuwSiFfYzyob2TteooA2xFfPvNTTfRa/NqiLU22i9n9IafjcGfyxQ5Bw+vIFJbJv7SnNW45c339PncpbpHskyyfcDHi2t2a6t80iuMaZXJwcoRss5/PN46GqVNv0MJKXhUQUijHgdkMVIhiTDTzEG8IDx5JaPR9pVEzINJBrtzxXzbbMD+CPMZgG0qWJ+8bLc2ljWK76vyouBjlIyZUNphfUknjGRvEDR851vfL2EPBCb/kdo8QxpEi+WHNJo4htV6vtetnMFwawavNt5LeSYMLf82BY6SOdcX8yGQ== nemesys@linuxmachine
    network_interfaces: interface
    image:
      offer: "{{ image_offer }}"
      publisher: "{{ image_publisher }}"
      sku: "{{ image_sku }}"
      version: "{{ image_version }}"
    custom_data: "{{ lookup('file', './tmp/cloud-init_tmp.yml') }}"
- debug:
    msg: " ### Lien de N8N: http://{{ fqdn }}.{{ local }}.cloudapp.azure.com ###"